project/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('detail/<slug:slug>/', views.post_detail, name='detail'),
    path('create/', views.post_create, name="create"),
    path('edit/<slug:slug>/', views.post_edit, name="edit"),
    path('categories/', views.category_list, name="categories"),
    path('categories/<single_slug>/', views.category_series, name="series"),
    path('categories/post/<slug>/', views.category_post, name="category_post"),
    path('categories/series/<slug>/', views.first_post, name="first_post"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('post.urls', namespace='post')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name="logout"),
    path('registration/', views.registration, name="registration"),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/post/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify

class Category(models.Model):
    category_name = models.CharField(max_length=200)
    category_description = models.CharField(max_length=200)
    category_slug = models.SlugField(max_length=200, default=1)

    def __str__(self):
        return self.category_name

class CategorySeries(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="categories", default=1)
    series_name = models.CharField(max_length=200)
    series_description = models.CharField(max_length=200)
    series_slug = models.SlugField(max_length=200)

    def __str__(self):
        return self.series_name

# Create your models here.
class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="post_categories", default=1)
    series = models.ForeignKey(CategorySeries, on_delete=models.CASCADE, related_name="category_series", default=1)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_user")
    content = RichTextUploadingField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug': self.slug})

def post_receiver(sender, instance, *args, **kwargs):
    slug = slugify(instance.title)

    exist = Post.objects.filter(slug=slug).exists()
    if exist:
        slug = "{}-{}".format(slug, instance.id)
    
    instance.slug = slug

def series_receiver(sender, instance, *args, **kwargs):
    slug = slugify(instance.series_name)

    exists = CategorySeries.objects.filter(series_slug=slug).exists()

    if exists:
        slug = "{}-{}".format(slug, instance.id)

    instance.series_slug = slug


pre_save.connect(receiver=post_receiver, sender=Post)
pre_save.connect(receiver=series_receiver, sender=CategorySeries)

project/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ['title', 'author', 'content']

project/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Post, Category, CategorySeries
from .forms import PostForm
from comment.forms import CommentForm
from django.contrib import messages

# Create your views here.
def category_list(request):
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'post/category_list.html', context)

def category_series(request, single_slug):
    category = get_object_or_404(Category, category_slug=single_slug)
    series = [c for c in category.categories.all()]
    posts = []
    for s in series:
        for post in s.category_series.all():
            posts.append(post)
    context = {'category':category, 'post':posts[0]}
    return render(request, 'post/category_series.html', context)

def first_post(request, slug):
    series = get_object_or_404(CategorySeries, series_slug=slug)
    posts = [post for post in series.category_series.all()]
    context = {'posts':posts, 'first_page':posts[0]}
    return render(request, 'post/first_post.html', context)

def category_post(request, slug):

    post = get_object_or_404(Post, slug=slug)
    categories = Post.objects.filter(series__series_name=post.series)

    context = {'posts': categories, 'first_page': post}
    return render(request, 'post/category_post.html', context)

def post_detail(request, slug=None):
    post = get_object_or_404(CategorySeries, series_slug=slug)
    form = CommentForm(request.POST or None)
    
    if form.is_valid():
        comment_form = form.save(commit=False)
        comment_form.post = post
        comment_form.save()

        return HttpResponseRedirect(post.get_absolute_url())

    context = {'posts': post, 'comment_form': form}
    return render(request, 'post/post_detail.html', context)

def post_create(request):
    post = Post.objects.all()
    form = PostForm(request.POST or None)
    update = False
    if form.is_valid():
        save = form.save()
        messages.success(request, f'{save.title} is created!')
        return HttpResponseRedirect(save.get_absolute_url())

    context = {'form': form, 'update':update}
    return render(request, 'post/post_form.html', context)

def post_edit(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, instance=post)
    update = True
    if form.is_valid():
        save = form.save()
        return HttpResponseRedirect(save.get_absolute_url())
    context = {'form': form, 'post': post, 'update': update}
    return render(request, 'post/post_form.html', context)

project/post/templates/post/category_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="card-panel">
            <h1>Welcome
                {% if user.is_authenticated %}
                <strong>{{ user.username | title }}!</strong>
                {% else %}
                <strong>Everyone!</strong>
                {% endif %}
            </h1>
        </div>
        <div class="row">
            {% for category in categories %}
    
            <div class="col s12 m4">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">{{ category.category_name|title }}</span>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'post:series' category.category_slug %}" class="waves-effect waves-light btn">
                            Read More
                        </a>
                    </div>
                </div>
    
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

project/post/templates/post/category_post.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col m8">
                <h1><a href="">{{ first_page.title|title }}</a></h1>
                <p>@{{first_page.author}} | {{ first_page.create_date }}</p>
                {{ first_page.content | safe }}
            </div>
            {% for post in posts.all %}
                <div class="col m4">
                    <ul class="collapsible">
                        <li>
                            <div class="collapsible-header">{{post.title|title}}</div>
                            <div class="collapsible-body"><span>
                                <a href="{% url 'post:category_post' post.slug %}" class="waves-effect waves-light btn">GO</a>
                            </span></div>
                        </li>
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

project/post/templates/post/category_series.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
        {% for s in category.categories.all %}
        <div class="col s12 m4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">{{ s.series_name|title }}</span>
                </div>
                <div class="card-action">
                    <a href="{% url 'post:first_post' s.series_slug %}" class="waves-effect waves-light btn">
                        Read More
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
</div>
{% endblock %}

project/post/templates/post/first_post.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col m8">
                <h1><a href="">{{ first_page.title|title }}</a></h1>
                <p>@{{first_page.author}} | {{ first_page.create_date }}</p>
                {{ first_page.content | safe }}
            </div>
            {% for post in posts %}
            <div class="col m4">
                <ul class="collapsible">
                    <li>
                        <div class="collapsible-header">{{post.title|title}}</div>
                        <div class="collapsible-body"><span>
                                <a href="{% url 'post:category_post' post.slug %}"
                                    class="waves-effect waves-light btn">GO</a>
                            </span></div>
                    </li>
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

project/post/templates/post/post_detail.html
{% extends 'main/base.html' %}    

{% block title%}{{ post.title }}{% endblock %}

{% block content %}
    <div class="container top-space">

        {% for post in posts.category_series.all %}
        <div class="row">
            <div class="col m10">
                <h1><a href="">{{ post.title|title }}</a></h1>
                <p>@{{post.author}} | {{ post.create_date }}</p>
                {{ post.content | safe }}

                {% block comments %}{% include 'comment/post_comment.html' %}{% endblock %}

                {% for comment in post.comments.all %}
                    <p><em>{{ user.username }}</em></p>
                    <p>{{ comment.text }}</p>
                    <hr>
                {% endfor %}
            </div>
        {% endfor %}
        </div>
        

    </div>
    

{% endblock %}

project/post/templates/post/post_form.html
{% extends 'main/base.html' %}
{% block title %}
    {% if update %}
        {{post.title}}
    {% else %}
        New Post
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container top-space">
        <form method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p}}
        
            <input type="submit" value="Submit" class="waves-effect waves-light btn">
        </form>
    </div>
{% endblock %}