project/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('detail/<slug:slug>/', views.post_detail, name='detail'),
    path('create/', views.post_create, name="create"),
    path('edit/<slug:slug>/', views.post_edit, name="edit"),
    path('categories/', views.category_list, name="categories"),
    path('categories/<single_slug>/', views.category_series, name="series"),
    path('categories/post/<slug>/', views.category_post, name="category_post"),
    path('categories/series/<slug>/', views.first_post, name="first_post"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('post.urls', namespace='post')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name="logout"),
    path('registration/', views.registration, name="registration"),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'post/css/materialize.min.css' %}">

    <!-- Hightlight -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <!-- materials icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'post/css/style.css' %}">

    
<body>
    <nav>
        <div class="my-container">
        <div class="nav-wrapper">
            <a href="{% url 'post:categories' %}" class="brand-logo"><strong>Turtlebot3</strong></a>
            <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="large material-icons">menu</i></a>

                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    {% if user.is_authenticated %}
                        <li class=""><a class="" href="{% url 'post:create' %}">Create Post</a></li>
                        <li class=""><a class="" href="">{{user.username}}</a></li>

                        <ul id="dropdown2" class="dropdown-content">
                            <li class=""><a class="" href="{% url 'admin:index' %}">Admin</a></li>
                            <li class=""><a class="" href="{% url 'logout' %}"><i class="large material-icons">exit_to_app</i></a></li>
                        </ul>
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2"><i
                                class="material-icons">person</i></a></li>
                    {% else %}
                        <li class=""><a class="waves-effect waves-light btn" href="{% url 'registration' %}">Register</a></li>
                        <li class=""><a class="" href="{% url 'login' %}">Login<i class="material-icons left">person</i></a></li>
                    {% endif %}
                </ul>
        </div>
        </div>
    </nav>

    
    <ul id="slide-out" class="sidenav">
        {% if user.is_authenticated %}
            <li class=""><a class="" href="{% url 'admin:index' %}">Admin</a></li>
            <li class=""><a class="" href="{% url 'post:create' %}">Create Post</a></li>
            <li class=""><a class="" href="">{{user.username}}</a></li>
            <li class=""><a class="" href="{% url 'logout' %}"><i class="material-icons">exit_to_app</i></a></li>

        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
        {% endif %}
    </ul>
    



    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

    <!-- materialized -->
    <!-- Compiled and minified JavaScript -->
    <script src="{% static 'post/js/materialize.min.js' %}"></script>



    {% if messages %}
        {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
        {% endfor %}
    {% endif %}

    <script>
            $(document).ready(function () {
                $('.sidenav').sidenav();
            });
        

            $(document).ready(function () {
                $('select').formSelect();
            });

            M.AutoInit();

            $(document).ready(function () {
                $('.collapsible').collapsible();
            });
        
    </script>

</body>
</html>

project/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <div class="container">
        <div class="card-panel">
            <h1>Welcome 
                {% if user.is_authenticated %}
                    <strong>{{ user.username | title }}!</strong>
                {% else %}
                    <strong>Everyone!</strong>
                {% endif %}
            </h1>
        </div>
    </div>
{% endblock %}

project/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <div class="container">
        <div class="card-panel">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Login" class="waves-effect waves-light btn">
            </form>
        </div>
    </div>
    
{% endblock %}

project/templates/main/registration.html
{% extends 'main/base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="container">
        <div class="card-panel">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register" class="waves-effect waves-light btn">
            </form>
        </div>
    </div>
{% endblock %}